/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import code.DBconnect;
import code.validate_1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HARIpc
 */
public class panel2 extends javax.swing.JPanel {

    Connection con=null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null;
    PreparedStatement pst3=null;
    
    ResultSet rs = null;
    ResultSet rs1=null;
    ResultSet rs2=null;
   
    DefaultTableModel dm;
    
    public panel2() {
        initComponents();
        
        //conncet to DB
        con = DBconnect.connect();
           
           //load table
        tableload1();
        fillSupplierCombo();
           
        product_namebox_label.setText("");
        buy_pricebox_label.setText("");
        sell_pricebox_label.setText("");
        sell_pricebox_label.setText("");
        mrpbox_label.setText("");
        reorder_levelbox_label.setText("");
        cont_sizebox_label.setText("");
            
    }
    
    
    public void fillSupplierCombo()
    {
        try
        {
            String sql="select comp_name from supplier";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String comboitems=rs.getString("comp_name");
                supplier_namebox.addItem(comboitems);
            }
        }
        catch(Exception e)
        {
            
        }
        
       
    }
    public void tableload1(){
        
        try{
        String sql = "SELECT prod_id as 'Product ID',size_1 as 'Size',prod_name as 'Product Name',supp_id as 'Supplier ID',comp_name as 'Supplier Name',buy_price as 'Buy',sell_price as 'Sell',mrp as 'MRP',quantity as 'Quantity',cate as 'Category',rol as 'Reorder Level',cont_size as 'Container Size',desc_1 as 'Description'  FROM product";
        pst = con.prepareStatement(sql);
        rs =pst.executeQuery(sql);
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
    }
    }
    
    public void filter(String query)
    {
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(dm);
        
        jTable1.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
        
    }
    /**

    /**
    * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_product = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        product_namebox = new javax.swing.JTextField();
        buy_pricebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        descriptionbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        product_idbox = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supplier_namebox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sizebox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sell_pricebox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        reorder_levelbox = new javax.swing.JTextField();
        supplier_idbox = new javax.swing.JLabel();
        category_box = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        product_namebox_label = new javax.swing.JLabel();
        buy_pricebox_label = new javax.swing.JLabel();
        reorder_levelbox_label = new javax.swing.JLabel();
        sell_pricebox_label = new javax.swing.JLabel();
        mrpbox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cont_sizebox = new javax.swing.JTextField();
        mrpbox_label = new javax.swing.JLabel();
        cont_sizebox_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        quantitybox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        view_product.setBackground(new java.awt.Color(51, 51, 51));
        view_product.setLayout(null);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        view_product.add(jScrollPane1);
        jScrollPane1.setBounds(10, 460, 850, 100);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product ID");
        view_product.add(jLabel1);
        jLabel1.setBounds(120, 60, 80, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier ID");
        view_product.add(jLabel2);
        jLabel2.setBounds(120, 110, 90, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");
        view_product.add(jLabel3);
        jLabel3.setBounds(440, 60, 110, 30);

        product_namebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        view_product.add(product_namebox);
        product_namebox.setBounds(580, 60, 170, 30);

        buy_pricebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        view_product.add(buy_pricebox);
        buy_pricebox.setBounds(240, 220, 160, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buying Price");
        view_product.add(jLabel5);
        jLabel5.setBounds(120, 210, 100, 38);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Supplier Name");
        view_product.add(jLabel9);
        jLabel9.setBounds(440, 110, 120, 30);

        descriptionbox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        view_product.add(descriptionbox);
        descriptionbox.setBounds(400, 370, 180, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description");
        view_product.add(jLabel6);
        jLabel6.setBounds(300, 370, 110, 30);

        search.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        view_product.add(search);
        search.setBounds(350, 10, 210, 30);

        product_idbox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        product_idbox.setForeground(new java.awt.Color(255, 255, 255));
        view_product.add(product_idbox);
        product_idbox.setBounds(240, 60, 160, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-undo-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        view_product.add(jButton2);
        jButton2.setBounds(200, 410, 150, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search ");
        view_product.add(jLabel4);
        jLabel4.setBounds(280, 10, 70, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Search-32.png"))); // NOI18N
        view_product.add(jLabel7);
        jLabel7.setBounds(570, 10, 40, 30);

        supplier_namebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        view_product.add(supplier_namebox);
        supplier_namebox.setBounds(580, 110, 170, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Size");
        view_product.add(jLabel8);
        jLabel8.setBounds(120, 160, 70, 30);

        sizebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sizebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25ml", "50ml", "60ml", "100ml", "120ml", "200ml", "400ml" }));
        view_product.add(sizebox);
        sizebox.setBounds(240, 160, 160, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Category");
        view_product.add(jLabel10);
        jLabel10.setBounds(440, 150, 110, 40);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Selling Price");
        view_product.add(jLabel11);
        jLabel11.setBounds(440, 220, 110, 30);

        sell_pricebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        view_product.add(sell_pricebox);
        sell_pricebox.setBounds(580, 220, 170, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reorder Level");
        view_product.add(jLabel12);
        jLabel12.setBounds(120, 320, 110, 30);

        reorder_levelbox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        reorder_levelbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorder_levelboxActionPerformed(evt);
            }
        });
        view_product.add(reorder_levelbox);
        reorder_levelbox.setBounds(240, 320, 160, 30);

        supplier_idbox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        supplier_idbox.setForeground(new java.awt.Color(255, 255, 255));
        view_product.add(supplier_idbox);
        supplier_idbox.setBounds(240, 110, 160, 30);

        category_box.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        category_box.setForeground(new java.awt.Color(255, 255, 255));
        view_product.add(category_box);
        category_box.setBounds(580, 160, 170, 30);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        view_product.add(jButton3);
        jButton3.setBounds(370, 410, 150, 40);

        product_namebox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        product_namebox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(product_namebox_label);
        product_namebox_label.setBounds(580, 90, 170, 20);

        buy_pricebox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        buy_pricebox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(buy_pricebox_label);
        buy_pricebox_label.setBounds(240, 250, 160, 20);

        reorder_levelbox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        reorder_levelbox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(reorder_levelbox_label);
        reorder_levelbox_label.setBounds(240, 350, 160, 20);

        sell_pricebox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sell_pricebox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(sell_pricebox_label);
        sell_pricebox_label.setBounds(580, 250, 170, 20);

        mrpbox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mrpbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrpboxActionPerformed(evt);
            }
        });
        view_product.add(mrpbox);
        mrpbox.setBounds(240, 270, 160, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MRP");
        view_product.add(jLabel13);
        jLabel13.setBounds(120, 280, 60, 14);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Container Size(ml)");
        view_product.add(jLabel14);
        jLabel14.setBounds(440, 320, 140, 30);

        cont_sizebox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cont_sizebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cont_sizeboxActionPerformed(evt);
            }
        });
        view_product.add(cont_sizebox);
        cont_sizebox.setBounds(580, 320, 170, 30);

        mrpbox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mrpbox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(mrpbox_label);
        mrpbox_label.setBounds(240, 300, 160, 20);

        cont_sizebox_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cont_sizebox_label.setForeground(new java.awt.Color(255, 0, 0));
        view_product.add(cont_sizebox_label);
        cont_sizebox_label.setBounds(580, 350, 170, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity");
        view_product.add(jLabel15);
        jLabel15.setBounds(440, 270, 110, 30);

        quantitybox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        quantitybox.setForeground(new java.awt.Color(255, 255, 255));
        view_product.add(quantitybox);
        quantitybox.setBounds(580, 270, 170, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/document-scroll-icon.png"))); // NOI18N
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        view_product.add(jButton1);
        jButton1.setBounds(530, 410, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view_product, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view_product, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r = jTable1.getSelectedRow();

        String product_id = jTable1.getValueAt(r ,0).toString();
        String size=jTable1.getValueAt(r,1).toString();
        String product_name = jTable1.getValueAt(r ,2).toString();
        String supplier_id = jTable1.getValueAt(r ,3).toString();
        String supplier_name=jTable1.getValueAt(r,4).toString();
        String buy_price = jTable1.getValueAt(r ,5).toString();
        String sell_price = jTable1.getValueAt(r ,6).toString();
        String mrp=jTable1.getValueAt(r ,7).toString();
        String quantity=jTable1.getValueAt(r ,8).toString();
        String category=jTable1.getValueAt(r,9).toString();
        String reorder_level = jTable1.getValueAt(r ,10).toString();
        String cont_size=jTable1.getValueAt(r ,11).toString();
        String description = jTable1.getValueAt(r ,12).toString();
        
        
        product_idbox.setText(product_id);
        product_namebox.setText(product_name);
        supplier_idbox.setText(supplier_id);
        supplier_namebox.setSelectedItem(supplier_name);
        sizebox.setSelectedItem(size);
        buy_pricebox.setText(buy_price);
        sell_pricebox.setText(sell_price);
        mrpbox.setText(mrp);
        quantitybox.setText(quantity);
        category_box.setText(category);
        reorder_levelbox.setText(reorder_level);
        cont_sizebox.setText(cont_size);
        descriptionbox.setText(description);

    }//GEN-LAST:event_jTable1MouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        
        DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
        String search1 = search.getText();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search1));
        
        
      
                
    }//GEN-LAST:event_searchKeyReleased

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int rowno=jTable1.getSelectedRow();
        
       if(rowno!=-1)
           
       {
           
       
        
        int count=0;
        boolean productname;
        boolean buyprice;
        boolean sellprice;
        boolean reorderlevel;
        boolean mrp1;
        boolean cont_size;
        
        
        validate_1 v2=new validate_1();
        productname=v2.check_letters(product_namebox.getText());
        buyprice=v2.doublecheck(buy_pricebox.getText());
        sellprice=v2.doublecheck(sell_pricebox.getText());
        mrp1=v2.doublecheck(mrpbox.getText());
        reorderlevel=v2.numcheck(reorder_levelbox.getText());
        cont_size=v2.numcheck(cont_sizebox.getText());
        
        if(productname==false)
        {
              product_namebox_label.setText("*Insert only letters");
              count++;
        }
        
        if(buyprice==false)
        {
              buy_pricebox_label.setText("*Insert only numerics");
              count++;
        }
        
         
        if(sellprice==false)
        {
              sell_pricebox_label.setText("*Insert only numerics");
              count++;
        }
        
        if(mrp1==false)
        {
              mrpbox_label.setText("*Insert only numerics");
              count++;
        }
         
        if(reorderlevel==false)
        {
              reorder_levelbox_label.setText("*Insert only numerics");
              count++;
        }
        
        if(cont_size==false)
        {
              cont_sizebox_label.setText("*Insert only numerics");
              count++;
        }
        
        if(count==0)
        {
        try{
            
            String value1=sizebox.getSelectedItem().toString();
            String value2=product_namebox.getText();
            String value3=supplier_namebox.getSelectedItem().toString();
            String value4=buy_pricebox.getText();
            String value5=sell_pricebox.getText();
            String value6=mrpbox.getText();
            String value7=reorder_levelbox.getText();
            String value8=cont_sizebox.getText();
            String value9=descriptionbox.getText();
            String value10=product_idbox.getText();
            
            String sql="update product set size_1='"+value1 +"',prod_name='"+value2+"',comp_name='"+value3+"',buy_price='"+value4+"',sell_price='"+value5+"',mrp='"+value6+"', rol='"+value7+"',cont_size='"+value8+"',desc_1='"+value9+"' where prod_id='"+value10+"' ";

            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated");

            product_namebox_label.setText("");
            buy_pricebox_label.setText("");
            sell_pricebox_label.setText("");
            mrpbox_label.setText("");
            reorder_levelbox_label.setText("");
            cont_sizebox_label.setText("");
                    
        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }

        tableload1();
        }
       }
       else
            JOptionPane.showMessageDialog(null,"Select a row");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void reorder_levelboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorder_levelboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reorder_levelboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int rowno=jTable1.getSelectedRow();
        
        if(rowno==-1)
        {
            JOptionPane.showMessageDialog(null,"Please Select a row to Delete");
        }
        
        else{
            
        
        String sql= "delete from product where prod_id=?";
        try{
        
        pst=con.prepareStatement(sql);
        
        pst.setString(1,product_idbox.getText());
        
        pst.execute();
        JOptionPane.showMessageDialog(null,"Deleted");
        
    
    }catch(Exception e){
    
        JOptionPane.showMessageDialog(null,e);
    }
        }
    tableload1(); //update table
                                  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cont_sizeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cont_sizeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cont_sizeboxActionPerformed

    private void mrpboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrpboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrpboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          try{
        String report="C:\\Users\\gange\\Desktop\\whd\\src\\Reports\\product.jrxml";
        JasperReport jr=JasperCompileManager.compileReport(report);
        JasperPrint jp=JasperFillManager.fillReport(jr,null,con);
        JasperViewer.viewReport(jp,false);
     
      } 
        catch(Exception e)
                {
                
                }
        
                       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buy_pricebox;
    private javax.swing.JLabel buy_pricebox_label;
    private javax.swing.JLabel category_box;
    private javax.swing.JTextField cont_sizebox;
    private javax.swing.JLabel cont_sizebox_label;
    private javax.swing.JTextField descriptionbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mrpbox;
    private javax.swing.JLabel mrpbox_label;
    private javax.swing.JLabel product_idbox;
    private javax.swing.JTextField product_namebox;
    private javax.swing.JLabel product_namebox_label;
    private javax.swing.JLabel quantitybox;
    private javax.swing.JTextField reorder_levelbox;
    private javax.swing.JLabel reorder_levelbox_label;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sell_pricebox;
    private javax.swing.JLabel sell_pricebox_label;
    private javax.swing.JComboBox<String> sizebox;
    private javax.swing.JLabel supplier_idbox;
    private javax.swing.JComboBox<String> supplier_namebox;
    private javax.swing.JPanel view_product;
    // End of variables declaration//GEN-END:variables
}
