/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;


import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;




/**
 *
 * @author vijeyaratnam
 */
public class duepayment extends javax.swing.JPanel {

   Connection con = null;
   ResultSet rs = null;
   PreparedStatement ps =null;
    
     String payid;
    public duepayment() {
        initComponents();
        
       // reset.setEnabled(false);
       // save.setEnabled(false);
        duedate1.setEnabled(false);
     
        update1.setEnabled(false);
        
        add2.setEnabled(false);
        update1.setEnabled(false);
        add3.setEnabled(false);
       
        
        collection2.setEnabled(false);
        duedate2.setEnabled(false);
        
        update2.setEnabled(false);
        
        if(!(collection_1.getText()==null))
        {
            duedate1.setEnabled(true);
            
            
        }
        
        if(!(collection2.getText()==null))
        {
            duedate2.setEnabled(true);
            
        }
        /*
        if(!(collection2.getText()==null))
        {
            collection2.setEnabled(true);
            duedate2.setEnabled(true);
            add2.setEnabled(true);
        }
        else 
        {
            collection2.setEnabled(false);
            duedate2.setEnabled(false);
            add2.setEnabled(false);
        }
        
         if(!(collection3.getText()==null))
        {
            collection3.setEnabled(true);
            duedate3.setEnabled(true);
            add3.setEnabled(true);
        }
         else
         {
             add3.setEnabled(false);
             update3.setEnabled(false);
         }
        */
        
        
       
        
        con =DBonnect.getConnection();
        
        view_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void genPayId1()
    {
        try{
            String sql = "Select pay_id from set_payment order by pay_id DESC LIMIT 1";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next())
            {
                String r1 = rs.getString("pay_id");
                int ln = r1.length();
                String stxt = r1.substring(0,2);
                String snum = r1.substring(2,ln);
                int n = Integer.parseInt(snum);
                n++;
                snum=Integer.toString(n);
                
                payid=stxt+snum;
                
            }
            else
            {
                payid = "pm111";
            }
            
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void view_table()
    {
        try{
            String sql = "Select d.deliveryID as 'Order Id', d.deliverydate as 'Delivery Date', od.total as 'Total Amount', r.ret_name as 'Retailer Name' from delivery d, order_1 o, retailer r, order_details od where d.deliverystatus = 'delivered' and o.ret_id=r.ret_id and d.deliveryID=o.ord_id and d.deliveryID=od.ord_id";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery(sql);
            duePayTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            System.out.println("error:"+e);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ordid = new javax.swing.JTextField();
        txt_retid = new javax.swing.JTextField();
        txt_retname = new javax.swing.JTextField();
        txt_deldate = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        collection_1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        duedate1 = new com.toedter.calendar.JDateChooser();
        label_msg1 = new javax.swing.JLabel();
        update1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        txt_payid = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        collection2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        duedate2 = new com.toedter.calendar.JDateChooser();
        label_msg2 = new javax.swing.JLabel();
        update2 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        txt_payid1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        collection3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        duedate3 = new com.toedter.calendar.JDateChooser();
        label_msg3 = new javax.swing.JLabel();
        add3 = new javax.swing.JButton();
        txt_payid2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        duePayTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(867, 559));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "General Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order ID");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 40, 82, 33);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retailer ID");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 100, 110, 23);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Retailer Name");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 150, 105, 23);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Delivery Date");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 200, 98, 23);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total Amount");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 250, 100, 23);

        txt_ordid.setEditable(false);
        txt_ordid.setBackground(new java.awt.Color(51, 51, 51));
        txt_ordid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ordid.setForeground(new java.awt.Color(255, 255, 255));
        txt_ordid.setText(":");
        txt_ordid.setBorder(null);
        txt_ordid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ordidActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ordid);
        txt_ordid.setBounds(230, 42, 150, 30);

        txt_retid.setEditable(false);
        txt_retid.setBackground(new java.awt.Color(51, 51, 51));
        txt_retid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_retid.setForeground(new java.awt.Color(255, 255, 255));
        txt_retid.setText(":");
        txt_retid.setBorder(null);
        jPanel2.add(txt_retid);
        txt_retid.setBounds(230, 92, 150, 30);

        txt_retname.setEditable(false);
        txt_retname.setBackground(new java.awt.Color(51, 51, 51));
        txt_retname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_retname.setForeground(new java.awt.Color(255, 255, 255));
        txt_retname.setText(":");
        txt_retname.setBorder(null);
        jPanel2.add(txt_retname);
        txt_retname.setBounds(230, 150, 150, 30);

        txt_deldate.setEditable(false);
        txt_deldate.setBackground(new java.awt.Color(51, 51, 51));
        txt_deldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_deldate.setForeground(new java.awt.Color(255, 255, 255));
        txt_deldate.setText(":");
        txt_deldate.setBorder(null);
        jPanel2.add(txt_deldate);
        txt_deldate.setBounds(230, 200, 150, 30);

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(51, 51, 51));
        txt_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 255, 255));
        txt_total.setText(":");
        txt_total.setBorder(null);
        jPanel2.add(txt_total);
        txt_total.setBounds(230, 250, 150, 30);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153)), "Collection Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1st Collection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount To Be Collected");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 50, 200, 23);

        collection_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collection_1ActionPerformed(evt);
            }
        });
        collection_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keytyped(evt);
            }
        });
        jPanel4.add(collection_1);
        collection_1.setBounds(230, 40, 130, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Due Date");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 100, 110, 23);

        duedate1.setDateFormatString("yyyy-M-d");
        jPanel4.add(duedate1);
        duedate1.setBounds(230, 90, 130, 30);

        label_msg1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label_msg1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(label_msg1);
        label_msg1.setBounds(20, 130, 360, 30);

        update1.setBackground(new java.awt.Color(51, 51, 51));
        update1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        update1.setForeground(new java.awt.Color(51, 51, 51));
        update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Restart_32px_1.png"))); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel4.add(update1);
        update1.setBounds(230, 170, 130, 41);

        add1.setBackground(new java.awt.Color(51, 51, 51));
        add1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add1.setForeground(new java.awt.Color(51, 51, 51));
        add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Plus_32px_1.png"))); // NOI18N
        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel4.add(add1);
        add1.setBounds(50, 170, 130, 41);

        txt_payid.setBackground(new java.awt.Color(51, 51, 51));
        txt_payid.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txt_payid);
        txt_payid.setBounds(230, 20, 120, 20);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 30, 400, 240);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2nd Collection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount To Be Collected");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, 60, 200, 23);

        collection2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collection2ActionPerformed(evt);
            }
        });
        jPanel5.add(collection2);
        collection2.setBounds(230, 50, 130, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Date");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(20, 100, 110, 23);

        duedate2.setDateFormatString("yyyy-M-d");
        jPanel5.add(duedate2);
        duedate2.setBounds(230, 100, 130, 30);

        label_msg2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label_msg2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(label_msg2);
        label_msg2.setBounds(20, 140, 360, 30);

        update2.setBackground(new java.awt.Color(51, 51, 51));
        update2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        update2.setForeground(new java.awt.Color(51, 51, 51));
        update2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Restart_32px_1.png"))); // NOI18N
        update2.setText("Update");
        update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ActionPerformed(evt);
            }
        });
        jPanel5.add(update2);
        update2.setBounds(230, 180, 130, 41);

        add2.setBackground(new java.awt.Color(51, 51, 51));
        add2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add2.setForeground(new java.awt.Color(51, 51, 51));
        add2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Plus_32px_1.png"))); // NOI18N
        add2.setText("Add");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        jPanel5.add(add2);
        add2.setBounds(50, 180, 130, 41);

        txt_payid1.setBackground(new java.awt.Color(51, 51, 51));
        txt_payid1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(txt_payid1);
        txt_payid1.setBounds(230, 30, 110, 0);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(20, 280, 400, 240);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3rd Collection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount To Be Collected");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 50, 200, 23);

        collection3.setEditable(false);
        collection3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collection3ActionPerformed(evt);
            }
        });
        jPanel6.add(collection3);
        collection3.setBounds(230, 50, 130, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Due Date");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 110, 110, 23);

        duedate3.setDateFormatString("yyyy-M-d");
        jPanel6.add(duedate3);
        duedate3.setBounds(230, 100, 130, 30);

        label_msg3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label_msg3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(label_msg3);
        label_msg3.setBounds(20, 140, 360, 30);

        add3.setBackground(new java.awt.Color(51, 51, 51));
        add3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add3.setForeground(new java.awt.Color(51, 51, 51));
        add3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Plus_32px_1.png"))); // NOI18N
        add3.setText("Add");
        add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ActionPerformed(evt);
            }
        });
        jPanel6.add(add3);
        add3.setBounds(140, 180, 130, 41);

        txt_payid2.setBackground(new java.awt.Color(51, 51, 51));
        txt_payid2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.add(txt_payid2);
        txt_payid2.setBounds(240, 20, 0, 0);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(20, 530, 400, 240);

        duePayTable.setBackground(new java.awt.Color(51, 51, 51));
        duePayTable.setForeground(new java.awt.Color(255, 255, 255));
        duePayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Retailer Name", "Total Amount", "Delivery Date"
            }
        ));
        duePayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duePayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(duePayTable);

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 344, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 870, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void duePayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duePayTableMouseClicked
        genPayId1();
        txt_payid.setText(payid);
        
        int row = duePayTable.getSelectedRow();
        String row_id = duePayTable.getValueAt(row, 0).toString();
        
        try{
            String q = "Select * from order_1 o, retailer r, delivery d, order_details od where o.ord_id = '"+row_id+"' and d.deliveryID=o.ord_id and o.ret_id=r.ret_id and d.deliveryID=od.ord_id";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            
            if (rs.next())
            {
                String OrderId = rs.getString("ord_id");
                String RetId = rs.getString("ret_id");
                String RetName = rs.getString("ret_name");
                String DeliDate = rs.getString("deliverydate");
                String total_ = rs.getString("od.total");
                txt_ordid.setText(OrderId);
                txt_retid.setText(RetId);
                txt_total.setText(total_);
                txt_retname.setText(RetName);
                txt_deldate.setText(DeliDate);
             }
            
            }
        
        catch( Exception e)
        {
            System.out.println(e);
        }
        
       /* try{
            String sql = "Select SUM(total) from order_1 where ord_id ='"+txt_ordid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            
            while(rs.next()){
                String total_ = rs.getString("SUM(total)");
                txt_total.setText(total_);
            }
        }
        catch(Exception e){
            
        }
        */
    }//GEN-LAST:event_duePayTableMouseClicked
    private void collection_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collection_1ActionPerformed
    
     
  
       
    }//GEN-LAST:event_collection_1ActionPerformed

    private void keytyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keytyped
      /*
        if(collection_1.getText().equals("")) 
     {
         add1.setEnabled(false);
         
         duedate1.setEnabled(false);
     }
     else 
     {
         add1.setEnabled(true);
         
         duedate1.setEnabled(true);
     }
    */
       
       
       
       
       
       char amt1 = evt.getKeyChar();
       
       if(!(Character.isDigit(amt1)|| (amt1 ==KeyEvent.VK_BACKSPACE) || amt1==KeyEvent.VK_DELETE))
       {
           evt.consume();
            JOptionPane.showMessageDialog(null, "Please enter only digits for Amount");
       }
       
       
    }//GEN-LAST:event_keytyped

    double Total;
    double Balance1;
    double Amount1;
    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
       
       
        
        payment p1 = new payment();
        
      
        
        //String ordID = txt_ordid.getText();
        
   int row_no = duePayTable.getSelectedRow();
    
    if (row_no == -1)
                {
                    JOptionPane.showMessageDialog(null, "Please select a row to Update");
                     update1.setEnabled(false);
                }
    else{
        
          double total = Double.parseDouble(txt_total.getText());
        Total = total;
        double amount1 = Double.parseDouble(collection_1.getText());
        Amount1 = amount1;
        double percent1 = ((amount1/total)*100);
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent1 = Double.parseDouble(df.format(percent1));
        
        double balance1 = total-amount1;
        Balance1 = balance1;
      // String row_id = duePayTable.getValueAt(row_no,0).toString();
          
       
        if (duedate1.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Due Date is required.");
       // update1.setEnabled(false);
        } 
        
        if(amount1>total)
        {
            label_msg1.setText("Amount should be less than " +total);
        }
         if(duedate1.getDate() == null || amount1>Total){
            jLabel3.setText("ccc");
        
        
        
        }
        else {
            
       SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
       String duedate = date_format.format(duedate1.getDate());
       
       p1.setPayId(txt_payid.getText());
       p1.setOrderId(txt_ordid.getText());
       p1.setRetId(txt_retid.getText());
       p1.setAmount(collection_1.getText());
       p1.setDueDate(duedate);
       String status = "Not Collected";
       p1.setStat(status);
       
       
       
       
       if(amount1==total)
       {
       int o = JOptionPane.showConfirmDialog(null,"Do you want to save final changes","Save",JOptionPane.YES_NO_OPTION);
       if(o==0){
       p1.sub_update(txt_ordid.getText());
       p1.connectDB();
       collection_1.setText("");
      duedate1.setDate(null);
       collection2.setText("");
       duedate2.setDate(null);
       collection3.setText("");
       duedate3.setDate(null);
       view_table();
       }
       }
       else{
           p1.connectDB();
         add1.setEnabled(false);
         add2.setEnabled(true);
         update1.setEnabled(true);
         collection2.setEnabled(true);
         label_msg1.setText(+trimpercent1+ "% of the total will be collected ");
         collection2.setText(String.valueOf(balance1));
         genPayId1();
         txt_payid1.setText(payid);
       }
        }
        
        
    }
    
  
    }//GEN-LAST:event_add1ActionPerformed
    double Amount2 ;
    double Amount3;
    double Balance2;
    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
       payment p1 = new payment();
        
        double amount2 = Double.parseDouble(collection2.getText());
        Amount2 = amount2;
        Amount3 = Amount1 + Amount2;
        double percent2 = ((Amount3/Total)*100);
        
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent2 = Double.parseDouble(df.format(percent2));
        
        double balance2 = Total-Amount3;
        Balance2 = balance2;
        
    int row_no = duePayTable.getSelectedRow();
    

    
    if (row_no == -1)
                {
                    JOptionPane.showMessageDialog(null, "Please select a row to Update");
                     update1.setEnabled(false);
                }
    else{
        //String row_id = duePayTable.getValueAt(row_no,0).toString();
          
     
       
        if (duedate2.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Due Date is required.");
       
        update2.setEnabled(false);
        } 
        
        if(duedate1.getDate().after(duedate2.getDate()))
        {
            label_msg2.setText("Date should be after first due date");
        }
        
        if(amount2>Total)
        {
            label_msg2.setText("Amount should be less than " +Balance1);
        }
        
        
        if(duedate2.getDate() == null || amount2>Total || duedate1.getDate().after(duedate2.getDate()) ) 
        {
            jLabel3.setText("ccc");
        
        }
        
        else {
            
       
             SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
       String duedate_2 = date_format.format(duedate2.getDate());
       
       p1.setPayId(txt_payid1.getText());
       p1.setOrderId(txt_ordid.getText());
       p1.setRetId(txt_retid.getText());
       p1.setAmount(collection2.getText());
       p1.setDueDate(duedate_2);
       String status = "Not Collected";
       p1.setStat(status);
       
       
       
       if(Amount3==Total)
       {
       int o = JOptionPane.showConfirmDialog(null,"Do you want to save final changes","Save",JOptionPane.YES_NO_OPTION);
       if(o==0){
           p1.connectDB();
       p1.sub_update(txt_ordid.getText());
       collection_1.setText("");
      duedate1.setDate(null);
       collection2.setText("");
       duedate2.setDate(null);
       collection3.setText("");
       duedate3.setDate(null);
       label_msg1.setText(null);
       view_table();
       }
       }
       else{
           p1.connectDB();
         if(Balance2 == 0.0)
         {
         add3.setEnabled(false);
         update2.setEnabled(true);
         }
         else
         {
         add3.setEnabled(true);    
         }
         add2.setEnabled(false);
         update1.setEnabled(true);
         collection3.setEnabled(true);
         label_msg2.setText(+trimpercent2+ "% of the total will be collected ");
         collection3.setText(String.valueOf(balance2));
         genPayId1();
         txt_payid2.setText(payid);
        }
        }
    }
    }//GEN-LAST:event_add2ActionPerformed
    double Amount4;
    double Amount5;
    private void add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ActionPerformed
        payment p1 = new payment();
        
        double amount4 = Double.parseDouble(collection3.getText());
        Amount4 = amount4;
        Amount5= Amount3 + Amount4;
        double percent3 = ((Amount4/Total)*100);
        
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent3 = Double.parseDouble(df.format(percent3));
        
            
    int row_no = duePayTable.getSelectedRow();
    
   
    
    if (row_no == -1)
                {
                    JOptionPane.showMessageDialog(null, "Please select a row to Update");
                }
    else{
       // String row_id = duePayTable.getValueAt(row_no,0).toString();
          
       
        if (duedate3.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Due Date is required.");
        } 
        
        if(duedate2.getDate().after(duedate3.getDate()))
        {
            label_msg3.setText("Date should be after second due date");
        }
        
        if(duedate3.getDate() == null || duedate2.getDate().after(duedate3.getDate()) ){
            jLabel3.setText("ccc");
        
        }
        
        
        else {
             SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
       String duedate_3 = date_format.format(duedate3.getDate());
       
       
       p1.setPayId(txt_payid2.getText());
       p1.setOrderId(txt_ordid.getText());
       p1.setRetId(txt_retid.getText());
       p1.setAmount(collection3.getText());
       p1.setDueDate(duedate_3);
       String status = "Not Collected";
       p1.setStat(status);
       
       
       if(Amount5==Total)
       {
       int o = JOptionPane.showConfirmDialog(null,"Do you want to save final changes","Save",JOptionPane.YES_NO_OPTION);
       if(o==0){
       p1.connectDB();
       p1.sub_update(txt_ordid.getText());
       collection_1.setText("");
      duedate1.setDate(null);
       collection2.setText("");
       duedate2.setDate(null);
       collection3.setText("");
       duedate3.setDate(null);
       label_msg1.setText(null);
       label_msg2.setText(null);

       view_table();
       }
       }
       
       else{
       //save.setEnabled(true);
       update2.setEnabled(true);
       
       add3.setEnabled(false);
       label_msg3.setText("The rest of "+trimpercent3+ "% of total will be collected ");
       //reset.setEnabled(true);
        }
        }
    }
    }//GEN-LAST:event_add3ActionPerformed

    private void collection2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collection2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collection2ActionPerformed

    private void txt_ordidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ordidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ordidActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
         payment p1 = new payment();
        
        
        
    int row_no = duePayTable.getSelectedRow();
    
    if (row_no == -1)
                {
                    JOptionPane.showMessageDialog(null, "Please select a row to Update");
                     update1.setEnabled(false);
                }
    else{
       // String row_id = duePayTable.getValueAt(row_no,0).toString();
          
       
        if (duedate1.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Due Date is required.");
        update1.setEnabled(false);
        } 
        double total = Double.parseDouble(txt_total.getText());
        Total = total;
        double amount1 = Double.parseDouble(collection_1.getText());
        Amount1 = amount1;
        double percent1 = ((amount1/total)*100);
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent1 = Double.parseDouble(df.format(percent1));
        
        double balance1 = total-amount1;
        Balance1 = balance1;
        
        if(amount1>total)
        {
            label_msg1.setText("Amount should be less than " +total);
        }
        else {
            
       SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
       String duedate = date_format.format(duedate1.getDate());
       
       p1.setPayId(txt_payid.getText());
       p1.setOrderId(txt_ordid.getText());
       p1.setRetId(txt_retid.getText());
       p1.setAmount(collection_1.getText());
       p1.setDueDate(duedate);
       
       p1.updateDB_1();
       update1.setEnabled(true);
         add1.setEnabled(false);
         add2.setEnabled(true);
         collection2.setEnabled(true);
         label_msg1.setText(+trimpercent1+ "% of the total will be collected ");
         collection2.setText(String.valueOf(balance1));
               
       
        }
    }
    }//GEN-LAST:event_update1ActionPerformed

    private void update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ActionPerformed
        payment p1 = new payment();
        
        double amount2 = Double.parseDouble(collection2.getText());
        Amount2 = amount2;
        Amount3 = Amount1 + Amount2;
        double percent2 = ((Amount3/Total)*100);
        
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent2 = Double.parseDouble(df.format(percent2));
        
        double balance2 = Total-Amount3;
        Balance2 = balance2;
        
    int row_no = duePayTable.getSelectedRow();
    
    if (row_no == -1)
                {
                    JOptionPane.showMessageDialog(null, "Please select a row to Update");
                     update1.setEnabled(false);
                }
    else{
        //String row_id = duePayTable.getValueAt(row_no,0).toString();
          
       
        if (duedate2.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Due Date is required.");
       
        update2.setEnabled(false);
        } 
        
        if(amount2>Total)
        {
            label_msg2.setText("Amount should be less than " +Balance1);
        }
        else {
            
       SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
       String duedate_2 = date_format.format(duedate2.getDate());
       
       p1.setPayId(txt_payid1.getText());
       p1.setOrderId(txt_ordid.getText());
       p1.setRetId(txt_retid.getText());
       p1.setAmount(collection2.getText());
       p1.setDueDate(duedate_2);
       
       p1.updateDB_1();
       if(Balance2 == 0.0)
         {
         add3.setEnabled(false);
         }
         else
         {
         add3.setEnabled(true);    
         }
         add2.setEnabled(false);
         update2.setEnabled(true);
         add1.setEnabled(false);
         add3.setEnabled(false);
         collection3.setEnabled(true);
         label_msg2.setText(+trimpercent2+ "% of the total will be collected ");
         collection3.setText(String.valueOf(balance2));
         
       
        }
    }
       
    }//GEN-LAST:event_update2ActionPerformed

    private void collection3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collection3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collection3ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JButton add3;
    private javax.swing.JTextField collection2;
    private javax.swing.JTextField collection3;
    private javax.swing.JTextField collection_1;
    private javax.swing.JTable duePayTable;
    private com.toedter.calendar.JDateChooser duedate1;
    private com.toedter.calendar.JDateChooser duedate2;
    private com.toedter.calendar.JDateChooser duedate3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_msg1;
    private javax.swing.JLabel label_msg2;
    private javax.swing.JLabel label_msg3;
    private javax.swing.JTextField txt_deldate;
    private javax.swing.JTextField txt_ordid;
    private javax.swing.JLabel txt_payid;
    private javax.swing.JLabel txt_payid1;
    private javax.swing.JLabel txt_payid2;
    private javax.swing.JTextField txt_retid;
    private javax.swing.JTextField txt_retname;
    private javax.swing.JTextField txt_total;
    private javax.swing.JButton update1;
    private javax.swing.JButton update2;
    // End of variables declaration//GEN-END:variables

    
}
