/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author gange
 */
public class homeUI extends javax.swing.JFrame {

    /**
     * Creates new form homeUI
     */
    
   
    
    public homeUI() {
        initComponents();
        
        setIcon();  //Setting the icon for the Jframe
        //Scroll to the bottom for the setIcon method code
        
        ////////Setting the current running system time to a label
        final DateFormat currtime = new SimpleDateFormat("HH:mm");
        final DateFormat currdate = new SimpleDateFormat("dd/MM/yyyy");
        int interval = 0; // 1000 ms

        new Timer(interval, new ActionListener() {
        //@Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            timelabel.setText(currtime.format(now.getTime()));
            datelabel.setText(currdate.format(now.getTime()));
        }
        }).start(); 
        //////////////////////////////////////////////////////////
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        delivery = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        duepayment = new javax.swing.JButton();
        salesorders = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        supplier = new javax.swing.JButton();
        finance = new javax.swing.JButton();
        damagehandle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Direct 2 Door");
        setBackground(new java.awt.Color(0, 131, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 700));

        delivery.setBackground(new java.awt.Color(51, 51, 51));
        delivery.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        delivery.setForeground(new java.awt.Color(255, 255, 255));
        delivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Delivery-64.png"))); // NOI18N
        delivery.setText("Delivery");
        delivery.setBorderPainted(false);
        delivery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delivery.setName("delivery"); // NOI18N
        delivery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveryMouseExited(evt);
            }
        });
        delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryActionPerformed(evt);
            }
        });

        inventory.setBackground(new java.awt.Color(51, 51, 51));
        inventory.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cardboard Box-64.png"))); // NOI18N
        inventory.setText("Inventory");
        inventory.setBorderPainted(false);
        inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventory.setFocusPainted(false);
        inventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventory.setName("inventory"); // NOI18N
        inventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryMouseExited(evt);
            }
        });
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        duepayment.setBackground(new java.awt.Color(51, 51, 51));
        duepayment.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        duepayment.setForeground(new java.awt.Color(255, 255, 255));
        duepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Payment History-64.png"))); // NOI18N
        duepayment.setText("Due Payment");
        duepayment.setBorderPainted(false);
        duepayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        duepayment.setName("delivery"); // NOI18N
        duepayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        duepayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duepaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duepaymentMouseExited(evt);
            }
        });
        duepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duepaymentActionPerformed(evt);
            }
        });

        salesorders.setBackground(new java.awt.Color(51, 51, 51));
        salesorders.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        salesorders.setForeground(new java.awt.Color(255, 255, 255));
        salesorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Shopping Cart Loaded-64.png"))); // NOI18N
        salesorders.setText("Sales & Orders");
        salesorders.setBorderPainted(false);
        salesorders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salesorders.setName("delivery"); // NOI18N
        salesorders.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salesorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesordersMouseExited(evt);
            }
        });
        salesorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesordersActionPerformed(evt);
            }
        });

        employee.setBackground(new java.awt.Color(51, 51, 51));
        employee.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Permanent Job-64.png"))); // NOI18N
        employee.setText("Employee");
        employee.setBorderPainted(false);
        employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee.setFocusPainted(false);
        employee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employee.setName("inventory"); // NOI18N
        employee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeMouseExited(evt);
            }
        });
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        supplier.setBackground(new java.awt.Color(51, 51, 51));
        supplier.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Supplier-64.png"))); // NOI18N
        supplier.setText("Supplier");
        supplier.setBorderPainted(false);
        supplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        supplier.setName("delivery"); // NOI18N
        supplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
        });
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });

        finance.setBackground(new java.awt.Color(51, 51, 51));
        finance.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        finance.setForeground(new java.awt.Color(255, 255, 255));
        finance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Sales Performance-64.png"))); // NOI18N
        finance.setText("Finance");
        finance.setBorderPainted(false);
        finance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finance.setName("delivery"); // NOI18N
        finance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        finance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                financeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                financeMouseExited(evt);
            }
        });
        finance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeActionPerformed(evt);
            }
        });

        damagehandle.setBackground(new java.awt.Color(51, 51, 51));
        damagehandle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        damagehandle.setForeground(new java.awt.Color(255, 255, 255));
        damagehandle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Factory-64.png"))); // NOI18N
        damagehandle.setText("Damage Handling");
        damagehandle.setBorderPainted(false);
        damagehandle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        damagehandle.setName("delivery"); // NOI18N
        damagehandle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        damagehandle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                damagehandleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                damagehandleMouseExited(evt);
            }
        });
        damagehandle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damagehandleActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/D2D.png"))); // NOI18N

        timelabel.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        timelabel.setForeground(new java.awt.Color(255, 255, 255));
        timelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        datelabel.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        datelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesorders, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(damagehandle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesorders, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(damagehandle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 1176, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseEntered
        inventory.setBackground(new Color(51,51,51).brighter());
        inventory.setSize(240,200);
    }//GEN-LAST:event_inventoryMouseEntered

    private void inventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseExited
       
        inventory.setBackground(new Color(51,51,51));
        inventory.setSize(217,184);
    }//GEN-LAST:event_inventoryMouseExited

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
        productUI inventory= new productUI();
        inventory.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_inventoryActionPerformed

    private void deliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryMouseEntered
        delivery.setBackground(new Color(51,51,51).brighter());
        delivery.setSize(240,200);
    }//GEN-LAST:event_deliveryMouseEntered

    private void deliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryMouseExited
        delivery.setBackground(new Color(51,51,51));
        delivery.setSize(217,184);
    }//GEN-LAST:event_deliveryMouseExited

    private void duepaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duepaymentMouseEntered
        duepayment.setBackground(new Color(51,51,51).brighter());
        duepayment.setSize(240,200);
        
    }//GEN-LAST:event_duepaymentMouseEntered

    private void duepaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duepaymentMouseExited
        duepayment.setBackground(new Color(51,51,51));
        duepayment.setSize(217,184);
    }//GEN-LAST:event_duepaymentMouseExited

    private void salesordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesordersMouseEntered
        salesorders.setBackground(new Color(51,51,51).brighter());
        salesorders.setSize(240,200);
    }//GEN-LAST:event_salesordersMouseEntered

    private void salesordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesordersMouseExited
        salesorders.setBackground(new Color(51,51,51));
        salesorders.setSize(217,184);
    }//GEN-LAST:event_salesordersMouseExited

    private void employeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseEntered
         employee.setBackground(new Color(51,51,51).brighter());
         employee.setSize(240,200);
    }//GEN-LAST:event_employeeMouseEntered

    private void employeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseExited
         employee.setBackground(new Color(51,51,51));
         employee.setSize(217,184);
    }//GEN-LAST:event_employeeMouseExited

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        employee log = new employee();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeeActionPerformed

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
        supplier.setBackground(new Color(51,51,51).brighter());
        supplier.setSize(240,200);
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        supplier.setBackground(new Color(51,51,51));
        supplier.setSize(217,184);
    }//GEN-LAST:event_supplierMouseExited

    private void financeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeMouseEntered
        finance.setBackground(new Color(51,51,51).brighter());
         finance.setSize(240,200);
    }//GEN-LAST:event_financeMouseEntered

    private void financeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeMouseExited
        finance.setBackground(new Color(51,51,51));
        finance.setSize(217,184);
    }//GEN-LAST:event_financeMouseExited

    private void damagehandleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damagehandleMouseEntered
        damagehandle.setBackground(new Color(51,51,51).brighter());
        damagehandle.setSize(240,200);
    }//GEN-LAST:event_damagehandleMouseEntered

    private void damagehandleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damagehandleMouseExited
        damagehandle.setBackground(new Color(51,51,51));
        damagehandle.setSize(217,184);
    }//GEN-LAST:event_damagehandleMouseExited

    private void deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryActionPerformed
       functionUI deliveryfunc = new functionUI();
       deliveryfunc.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_deliveryActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        // TODO add your handling code here:
        supplierUI log = new supplierUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierActionPerformed

    private void damagehandleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagehandleActionPerformed
        // TODO add your handling code here:
        damageUI log = null;
        try {
            log = new damageUI();
        } catch (SQLException ex) {
            Logger.getLogger(homeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        log.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_damagehandleActionPerformed

    private void financeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeActionPerformed
        // TODO add your handling code here:
        financeUI log = new financeUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financeActionPerformed

    private void salesordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesordersActionPerformed
        // TODO add your handling code here:
        order_salesUI log = new order_salesUI();
        log.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_salesordersActionPerformed

    private void duepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duepaymentActionPerformed
        // TODO add your handling code here:
        DuePaymentUI log = new DuePaymentUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_duepaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton damagehandle;
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton delivery;
    private javax.swing.JButton duepayment;
    private javax.swing.JButton employee;
    private javax.swing.JButton finance;
    private javax.swing.JButton inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salesorders;
    private javax.swing.JButton supplier;
    private javax.swing.JLabel timelabel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icons8-Depot-16.png")));
    
    }
}
