/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;


import Class.validation;
import Class.Payment;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mudara Bandaranayake
 */
public class panelSupppayment extends javax.swing.JPanel {

    /**
     * Creates new form panelSupppayment
     */
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    Date currentdate = new Date();
    public panelSupppayment() {
        initComponents();
        Payment pay=new Payment();
        ResultSet result=pay.getStocks();
        try{
        while(result.next()){
                String stoc_id=result.getString("stoc_id");
                StockCombo.addItem(stoc_id);
            }
        }
        catch(Exception e){
            
        }
                payidField.setText("");
                suppidField.setText("");
                amountField.setText("");
                pamountField.setText("");
                ddateField.setDate(null);
                pdateField.setDate(null);
                comField.setText("");
                remainField.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        payidLabel = new javax.swing.JLabel();
        stockidLabel = new javax.swing.JLabel();
        ddateLabel = new javax.swing.JLabel();
        pamountLabel = new javax.swing.JLabel();
        pdateLabel = new javax.swing.JLabel();
        comLabel = new javax.swing.JLabel();
        suppidField = new javax.swing.JLabel();
        suppidLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JLabel();
        ddateField = new com.toedter.calendar.JDateChooser();
        pdateField = new com.toedter.calendar.JDateChooser();
        payidField = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        pamountField = new javax.swing.JTextField();
        remainLabel = new javax.swing.JLabel();
        comField = new javax.swing.JLabel();
        remainField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StockCombo = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CalculateBtn = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        SPLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 300));

        payidLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        payidLabel.setForeground(new java.awt.Color(255, 255, 255));
        payidLabel.setText("Payment ID :");

        stockidLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        stockidLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockidLabel.setText("Stock ID :");

        ddateLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ddateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ddateLabel.setText("Due Date :");

        pamountLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pamountLabel.setForeground(new java.awt.Color(255, 255, 255));
        pamountLabel.setText("Paid Amount :");

        pdateLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pdateLabel.setForeground(new java.awt.Color(255, 255, 255));
        pdateLabel.setText("Paid Date :");

        comLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comLabel.setForeground(new java.awt.Color(255, 255, 255));
        comLabel.setText("Commission:");

        suppidField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        suppidField.setForeground(new java.awt.Color(255, 255, 255));

        suppidLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        suppidLabel.setForeground(new java.awt.Color(255, 255, 255));
        suppidLabel.setText("Supplier ID :");

        amountField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        amountField.setForeground(new java.awt.Color(255, 255, 255));

        payidField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        payidField.setForeground(new java.awt.Color(255, 255, 255));

        amountLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel.setText("Amount :");

        remainLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remainLabel.setForeground(new java.awt.Color(255, 255, 255));
        remainLabel.setText("Remaining :");

        comField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comField.setForeground(new java.awt.Color(255, 255, 255));

        remainField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remainField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));

        StockCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StockComboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stockidLabel)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(payidLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(payidField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StockCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ddateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddateField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(comLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addComponent(comField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(remainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(remainField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pdateLabel)
                            .addComponent(suppidLabel)
                            .addComponent(pamountLabel)
                            .addComponent(amountLabel))
                        .addGap(66, 66, 66)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pamountField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pdateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(suppidField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockidLabel)
                    .addComponent(StockCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suppidField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(payidField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suppidLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(payidLabel)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pdateLabel)
                                .addComponent(ddateLabel))
                            .addComponent(ddateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(pamountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comLabel)
                                            .addComponent(comField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(remainField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(remainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(pamountLabel)
                                        .addGap(41, 41, 41)
                                        .addComponent(amountLabel)))
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        updateBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-undo-icon.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PaymentID", "SupplierID", "OrderID", "Amountl", "DueDate", "PaidDate", "Commission", "PaidAmount"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        removeBtn.setBackground(new java.awt.Color(51, 51, 51));
        removeBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-delete-icon.png"))); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));

        CalculateBtn.setBackground(new java.awt.Color(51, 51, 51));
        CalculateBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CalculateBtn.setForeground(new java.awt.Color(255, 255, 255));
        CalculateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POS Terminal_48px.png"))); // NOI18N
        CalculateBtn.setText("Calculate");
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        completeBtn.setBackground(new java.awt.Color(51, 51, 51));
        completeBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        completeBtn.setForeground(new java.awt.Color(255, 255, 255));
        completeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POS Terminal_48px.png"))); // NOI18N
        completeBtn.setText("Completed");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(51, 51, 51));
        resetBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-undo-icon.png"))); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        SPLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SPLabel.setForeground(new java.awt.Color(255, 255, 255));
        SPLabel.setText("Supplier Payment");

        durationLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CalculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(completeBtn)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(SPLabel)
                .addGap(109, 109, 109)
                .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(durationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn)
                            .addComponent(removeBtn)
                            .addComponent(resetBtn)
                            .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        Payment pay=new Payment();
        int n = JOptionPane.showConfirmDialog(
                            null, "Are You Sure You Want To Delete?",
                            "Delete?",
                            JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.YES_OPTION) {
                 pay.remove((String) StockCombo.getSelectedItem());
                 JOptionPane.showMessageDialog(null,"Record removed.","Action Successful",
                JOptionPane.PLAIN_MESSAGE);
                 }
                else  {
                    JOptionPane.showMessageDialog(null,"Record not Removed.","Action Successful",
                JOptionPane.PLAIN_MESSAGE);
                }  
        ResultSet result=pay.searchAll();
        try {
                jTable1.setModel(DbUtils.resultSetToTableModel(result));

             } catch (Exception ex) {
            Logger.getLogger(panelSupppayment.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_removeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        Payment pay=new Payment();
        double extrapaid=pay.getExtrapaid(suppidField.getText());
        if(pamountField.getText().equals("")||ddateField.getDate().toString().equals("")||pdateField.getDate().toString().equals("")){
        validation valid=new validation();
        valid.isBlank(pamountField.getText(),jLabel4);
        valid.dateBlank(ddateField.getDate(),jLabel2);
        valid.dateBlank(pdateField.getDate(),jLabel3);
        }
        else if(!validation.doublecheck(pamountField.getText())){
          jLabel4.setText("Please Enter a Valid amount");  
        }
        else{
        pay.setpdue_date(ddateField.getDate());
        pay.setpaid_date(pdateField.getDate());
        double pamount=Double.parseDouble(pamountField.getText())+extrapaid;
        pay.setpaid_amount(pamount);
        double remaining=Double.parseDouble(remainField.getText());
        remaining=(remaining-pamount);
        remainField.setText(Double.toString(remaining));
        pay.setpay_remain(Double.parseDouble(remainField.getText()));
        if(remaining<=0){
         extrapaid=(-1*(remaining));
         remaining=0;
         remainField.setText("Your Payment is Complete.");
         pay.setpay_remain(remaining);
         pay.updateExtrapaid(suppidField.getText(),extrapaid);
         pay.updatePaystatus((String) StockCombo.getSelectedItem());
        }
        else{
        extrapaid=0;
        pay.updateExtrapaid(suppidField.getText(),extrapaid);
        }
        pay.update((String) StockCombo.getSelectedItem());
        StockCombo.removeAllItems();
        ResultSet result=pay.getStocks();
        try{
        while(result.next()){
                String stocid=result.getString("stoc_id");
                StockCombo.addItem(stocid);
            }
        }
        catch(Exception e){
                System.out.println(e);
        } 
        ResultSet result1=pay.searchAll();
        try {
            
                jTable1.setModel(DbUtils.resultSetToTableModel(result1));
            }
        catch (Exception ex) {
            Logger.getLogger(panelSupppayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        }   
    }//GEN-LAST:event_updateBtnActionPerformed

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
        // TODO add your handling code here:
        Payment pay=new Payment();
        pay.findAmount((String) StockCombo.getSelectedItem());
        ResultSet result2=pay.loadData((String) StockCombo.getSelectedItem());
        try {
            while(result2.next()){
                String suppayid  = result2.getString("suppay_id");
                String suppid  = result2.getString("supp_id");
                //String stoc_id  = result2.getString("stoc_id");
                String amount  = result2.getString("amount");
                Date pduedate  = result2.getDate("pdue_date");
                String commission  = result2.getString("commission");
                String payremain  = result2.getString("pay_remain");
                payidField.setText(suppayid);
                suppidField.setText(suppid);
                amountField.setText(amount);
                ddateField.setDate(pduedate);
                comField.setText(commission);
                remainField.setText(payremain);
                JOptionPane.showMessageDialog(null,"Payment Calculated.","Action Successful",
                JOptionPane.PLAIN_MESSAGE);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelSupppayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Done");
          
    }//GEN-LAST:event_CalculateBtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        Payment pay=new Payment();
        ResultSet result=pay.viewCompleted();
         try {
         jTable1.setModel(DbUtils.resultSetToTableModel(result));
         JOptionPane.showMessageDialog(null,"Completed Payments will be shown.","Action Successful",
                JOptionPane.PLAIN_MESSAGE);
           
        }catch (Exception ex) {
            Logger.getLogger(panelSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_completeBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
                payidField.setText("");
                suppidField.setText("");
                amountField.setText("");
                pamountField.setText("");
                ddateField.setDate(null);
                pdateField.setDate(null);
                comField.setText("");
                remainField.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void StockComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StockComboItemStateChanged
        // TODO add your handling code here:
                durationLabel.setText("");
                payidField.setText("");
                suppidField.setText("");
                amountField.setText("");
                pamountField.setText("");
                ddateField.setDate(null);
                pdateField.setDate(null);
                comField.setText("");
                remainField.setText("");
                Payment pay=new Payment();
                ResultSet result2=pay.loadData((String) StockCombo.getSelectedItem());
                try {
                while(result2.next()){
                    String suppay_id  = result2.getString("suppay_id");
                    String supp_id  = result2.getString("supp_id");
                    String amount  = result2.getString("amount");
                    Date pduedate  = result2.getDate("pdue_date");
                    String commission  = result2.getString("commission");
                    String pay_remain  = result2.getString("pay_remain");
                    payidField.setText(suppay_id);
                    suppidField.setText(supp_id);
                    amountField.setText(amount);
                    ddateField.setDate(pduedate);
                    comField.setText(commission);
                    remainField.setText(pay_remain);
                    int duration=pay.getDuration(currentdate,pduedate);
                    if(duration<0){
                    durationLabel.setText("Duedate has exceeded.");    
                    }
                    else{
                    durationLabel.setText(duration+" days to settle the payment.");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(panelSupppayment.class.getName()).log(Level.SEVERE, null, ex);
            }  
            boolean bool=pay.showLabel((String) StockCombo.getSelectedItem());
                if(bool==true ){
                 jLabel1.setText("Pending Payment");
                 CalculateBtn.setEnabled(false);
                }
                else{
                 jLabel1.setText("Calculate");
                 CalculateBtn.setEnabled(true);
                }
        ResultSet result=pay.search((String) StockCombo.getSelectedItem());
        try {
                jTable1.setModel(DbUtils.resultSetToTableModel(result));
            } 
         catch (Exception ex) {
            Logger.getLogger(panelSupppayment.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_StockComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JLabel SPLabel;
    private javax.swing.JComboBox<String> StockCombo;
    private javax.swing.JLabel amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel comField;
    private javax.swing.JLabel comLabel;
    private javax.swing.JButton completeBtn;
    private com.toedter.calendar.JDateChooser ddateField;
    private javax.swing.JLabel ddateLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pamountField;
    private javax.swing.JLabel pamountLabel;
    private javax.swing.JLabel payidField;
    private javax.swing.JLabel payidLabel;
    private com.toedter.calendar.JDateChooser pdateField;
    private javax.swing.JLabel pdateLabel;
    private javax.swing.JLabel remainField;
    private javax.swing.JLabel remainLabel;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel stockidLabel;
    private javax.swing.JLabel suppidField;
    private javax.swing.JLabel suppidLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
