/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import interf.panel2;
import interf.panel1;
import code.DBconnect;
import code.product_1;
import interf.reorder;
import interf.stock;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gange
 */
public class productUI extends javax.swing.JFrame {

    GridBagLayout layout=new GridBagLayout();
   
    panel1 p1;
    panel2 p2;
    stock p3;
    reorder p4;
    
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    /**
     * Creates new form add_product
     */
    
   
    /**
     * Creates new form functionUI
     */
    public productUI() {
        initComponents();
        
        p1=new panel1();
        p2=new panel2();
        p3=new stock();
        p4=new reorder();
       
        
        jPanel3.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        
        c.gridx=0;
        c.gridy=0;
        jPanel3.add(p1,c);
        
        c.gridx=0;
        c.gridy=0;
        jPanel3.add(p2,c);
        
        c.gridx=0;
        c.gridy=0;
        jPanel3.add(p3,c);
        
        c.gridx=0;
        c.gridy=0;
        jPanel3.add(p4,c);
        
       
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false); 
        p4.setVisible(false);
        
        con = DBconnect.connect();
    }

     
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topdelivery = new javax.swing.JButton();
        topduepayment = new javax.swing.JButton();
        topsalesorders = new javax.swing.JButton();
        topemployee = new javax.swing.JButton();
        topsupplier = new javax.swing.JButton();
        topfinance = new javax.swing.JButton();
        topdamagehandle = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 700));

        topdelivery.setBackground(new java.awt.Color(51, 51, 51));
        topdelivery.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topdelivery.setForeground(new java.awt.Color(255, 255, 255));
        topdelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Delivery-64.png"))); // NOI18N
        topdelivery.setText("Delivery");
        topdelivery.setBorder(null);
        topdelivery.setBorderPainted(false);
        topdelivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topdelivery.setFocusPainted(false);
        topdelivery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topdelivery.setName("topdelivery"); // NOI18N
        topdelivery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topdelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topdeliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topdeliveryMouseExited(evt);
            }
        });
        topdelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topdeliveryActionPerformed(evt);
            }
        });

        topduepayment.setBackground(new java.awt.Color(51, 51, 51));
        topduepayment.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topduepayment.setForeground(new java.awt.Color(255, 255, 255));
        topduepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Payment History-64.png"))); // NOI18N
        topduepayment.setText("Due Payment");
        topduepayment.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        topduepayment.setBorderPainted(false);
        topduepayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topduepayment.setName("delivery"); // NOI18N
        topduepayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topduepayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topduepaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topduepaymentMouseExited(evt);
            }
        });
        topduepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topduepaymentActionPerformed(evt);
            }
        });

        topsalesorders.setBackground(new java.awt.Color(51, 51, 51));
        topsalesorders.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topsalesorders.setForeground(new java.awt.Color(255, 255, 255));
        topsalesorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Shopping Cart Loaded-64.png"))); // NOI18N
        topsalesorders.setText("Sales & Orders");
        topsalesorders.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        topsalesorders.setBorderPainted(false);
        topsalesorders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topsalesorders.setName("delivery"); // NOI18N
        topsalesorders.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topsalesorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topsalesordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topsalesordersMouseExited(evt);
            }
        });
        topsalesorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topsalesordersActionPerformed(evt);
            }
        });

        topemployee.setBackground(new java.awt.Color(51, 51, 51));
        topemployee.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topemployee.setForeground(new java.awt.Color(255, 255, 255));
        topemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Permanent Job-64.png"))); // NOI18N
        topemployee.setText("Employee");
        topemployee.setBorder(null);
        topemployee.setBorderPainted(false);
        topemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topemployee.setFocusPainted(false);
        topemployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topemployee.setName("inventory"); // NOI18N
        topemployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topemployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topemployeeMouseExited(evt);
            }
        });
        topemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topemployeeActionPerformed(evt);
            }
        });

        topsupplier.setBackground(new java.awt.Color(51, 51, 51));
        topsupplier.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topsupplier.setForeground(new java.awt.Color(255, 255, 255));
        topsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Supplier-64.png"))); // NOI18N
        topsupplier.setText("Supplier");
        topsupplier.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        topsupplier.setBorderPainted(false);
        topsupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topsupplier.setName("delivery"); // NOI18N
        topsupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topsupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topsupplierMouseExited(evt);
            }
        });
        topsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topsupplierActionPerformed(evt);
            }
        });

        topfinance.setBackground(new java.awt.Color(51, 51, 51));
        topfinance.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topfinance.setForeground(new java.awt.Color(255, 255, 255));
        topfinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Sales Performance-64.png"))); // NOI18N
        topfinance.setText("Finance");
        topfinance.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        topfinance.setBorderPainted(false);
        topfinance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topfinance.setName("delivery"); // NOI18N
        topfinance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topfinance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topfinanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topfinanceMouseExited(evt);
            }
        });
        topfinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topfinanceActionPerformed(evt);
            }
        });

        topdamagehandle.setBackground(new java.awt.Color(51, 51, 51));
        topdamagehandle.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        topdamagehandle.setForeground(new java.awt.Color(255, 255, 255));
        topdamagehandle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Factory-64.png"))); // NOI18N
        topdamagehandle.setText("Damage Handling");
        topdamagehandle.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        topdamagehandle.setBorderPainted(false);
        topdamagehandle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topdamagehandle.setName("delivery"); // NOI18N
        topdamagehandle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topdamagehandle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topdamagehandleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topdamagehandleMouseExited(evt);
            }
        });
        topdamagehandle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topdamagehandleActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(51, 51, 51));
        home.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8-Home-64.png"))); // NOI18N
        home.setText("Home");
        home.setBorder(null);
        home.setBorderPainted(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setFocusPainted(false);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setName("topinventory"); // NOI18N
        home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Product Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Stocks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reorder");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(topdelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topduepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topsalesorders, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(topemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(topfinance, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topdamagehandle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topdamagehandle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topfinance, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topsalesorders, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topduepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topdelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topdeliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topdeliveryMouseEntered
        topdelivery.setBackground(new Color(51,51,51).brighter());
        topdelivery.setSize(131,120);
    }//GEN-LAST:event_topdeliveryMouseEntered

    private void topdeliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topdeliveryMouseExited

        topdelivery.setBackground(new Color(51,51,51));
        topdelivery.setSize(131,108);
    }//GEN-LAST:event_topdeliveryMouseExited

    private void topdeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topdeliveryActionPerformed
        functionUI deliveryfunc = new functionUI();
       deliveryfunc.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_topdeliveryActionPerformed

    private void topduepaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topduepaymentMouseEntered
        topduepayment.setBackground(new Color(51,51,51).brighter());
        topduepayment.setSize(131,120);

    }//GEN-LAST:event_topduepaymentMouseEntered

    private void topduepaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topduepaymentMouseExited
        topduepayment.setBackground(new Color(51,51,51));
        topduepayment.setSize(131,108);
    }//GEN-LAST:event_topduepaymentMouseExited

    private void topsalesordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topsalesordersMouseEntered
        topsalesorders.setBackground(new Color(51,51,51).brighter());
        topsalesorders.setSize(131,120);
    }//GEN-LAST:event_topsalesordersMouseEntered

    private void topsalesordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topsalesordersMouseExited
        topsalesorders.setBackground(new Color(51,51,51));
        topsalesorders.setSize(131,108);
    }//GEN-LAST:event_topsalesordersMouseExited

    private void topemployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topemployeeMouseEntered
        topemployee.setBackground(new Color(51,51,51).brighter());
        topemployee.setSize(131,120);
    }//GEN-LAST:event_topemployeeMouseEntered

    private void topemployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topemployeeMouseExited
        topemployee.setBackground(new Color(51,51,51));
        topemployee.setSize(131,108);
    }//GEN-LAST:event_topemployeeMouseExited

    private void topemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topemployeeActionPerformed
        employee log = new employee();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topemployeeActionPerformed

    private void topsupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topsupplierMouseEntered
        topsupplier.setBackground(new Color(51,51,51).brighter());
        topsupplier.setSize(131,120);
    }//GEN-LAST:event_topsupplierMouseEntered

    private void topsupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topsupplierMouseExited
        topsupplier.setBackground(new Color(51,51,51));
        topsupplier.setSize(131,108);
    }//GEN-LAST:event_topsupplierMouseExited

    private void topfinanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topfinanceMouseEntered
        topfinance.setBackground(new Color(51,51,51).brighter());
        topfinance.setSize(131,120);
    }//GEN-LAST:event_topfinanceMouseEntered

    private void topfinanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topfinanceMouseExited
        topfinance.setBackground(new Color(51,51,51));
        topfinance.setSize(131,108);
    }//GEN-LAST:event_topfinanceMouseExited

    private void topdamagehandleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topdamagehandleMouseEntered
        topdamagehandle.setBackground(new Color(51,51,51).brighter());
        topdamagehandle.setSize(131,120);
    }//GEN-LAST:event_topdamagehandleMouseEntered

    private void topdamagehandleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topdamagehandleMouseExited
        topdamagehandle.setBackground(new Color(51,51,51));
        topdamagehandle.setSize(131,108);
    }//GEN-LAST:event_topdamagehandleMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(new Color(51,51,51).brighter());
        home.setSize(131,120);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(new Color(51,51,51));
        home.setSize(131,108);
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        homeUI gohome = new homeUI();
        gohome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
       p2.tableload1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p3.tableload();
        
       
        p3.fillProductCombo();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void topduepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topduepaymentActionPerformed
        DuePaymentUI log = new DuePaymentUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topduepaymentActionPerformed

    private void topsalesordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topsalesordersActionPerformed
        order_salesUI log = new order_salesUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topsalesordersActionPerformed

    private void topsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topsupplierActionPerformed
       supplierUI log = new supplierUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topsupplierActionPerformed

    private void topfinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topfinanceActionPerformed
        financeUI log = new financeUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topfinanceActionPerformed

    private void topdamagehandleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topdamagehandleActionPerformed
       damageUI log = null;
        try {
            log = new damageUI();
        } catch (SQLException ex) {
            Logger.getLogger(homeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_topdamagehandleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton topdamagehandle;
    private javax.swing.JButton topdelivery;
    private javax.swing.JButton topduepayment;
    private javax.swing.JButton topemployee;
    private javax.swing.JButton topfinance;
    private javax.swing.JButton topsalesorders;
    private javax.swing.JButton topsupplier;
    // End of variables declaration//GEN-END:variables
}
