/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author vijeyaratnam
 */
public class setpayment extends javax.swing.JPanel {
      java.sql.Connection con = null;
   ResultSet rs = null;
   PreparedStatement ps =null;
    /**
     * Creates new form setpayment
     */
    public setpayment() {
        initComponents();
        
        
        
        jLabel4.setVisible(false);
         // coldate.setEnabled(false);
    
          
        con = DBonnect.getConnection();
        
        view_table();
    }
    
    private void view_table()
    {
        try{
           // String sql = "Select p.ord_id as 'Order Id', p.pay_id as 'Payment Id', r.ret_name as 'Retailer Name', p.amou as 'Amount', p.stat as 'Status' from set_payment p, retailer r where p.ret_id=r.ret_id ";
            String sql = "select set_payment.ord_id as 'Order ID',retailer.ret_name as 'Retailer Name',SUM(set_payment.amou) as 'Amount' from set_payment INNER JOIN retailer ON set_payment.ret_id=retailer.ret_id group by set_payment.ord_id";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery(sql);
            set_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            System.out.println("error:"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        set_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_ordid = new javax.swing.JTextField();
        txt_retid = new javax.swing.JTextField();
        txt_retname = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        colstat = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        coldate = new com.toedter.calendar.JDateChooser();
        addbutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_pay_id_1 = new javax.swing.JTextField();
        due_date = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txt_delidate = new com.toedter.calendar.JDateChooser();
        txt_total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_history = new javax.swing.JTable();
        lbl_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ptotal = new javax.swing.JLabel();
        lbl_percent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        retailer_mail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1112, 1200));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        set_table.setBackground(new java.awt.Color(51, 51, 51));
        set_table.setForeground(new java.awt.Color(255, 255, 255));
        set_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Retailer Name", "Amount"
            }
        ));
        set_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(set_table);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "General Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Order ID");

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Retailer ID");

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Retailer Name");

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Delivery Date");

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total Order Amount");

        txt_ordid.setEditable(false);
        txt_ordid.setBackground(new java.awt.Color(51, 51, 51));
        txt_ordid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_ordid.setForeground(new java.awt.Color(255, 255, 255));
        txt_ordid.setBorder(null);
        txt_ordid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ordidActionPerformed(evt);
            }
        });

        txt_retid.setEditable(false);
        txt_retid.setBackground(new java.awt.Color(51, 51, 51));
        txt_retid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_retid.setForeground(new java.awt.Color(255, 255, 255));
        txt_retid.setBorder(null);

        txt_retname.setEditable(false);
        txt_retname.setBackground(new java.awt.Color(51, 51, 51));
        txt_retname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_retname.setForeground(new java.awt.Color(255, 255, 255));
        txt_retname.setBorder(null);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Collection Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Amount");

        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Status");

        colstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Collected", "Collected" }));
        colstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colstatActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Collection Date");

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Due Date");

        coldate.setDateFormatString("yyyy-M-d");

        addbutton.setBackground(new java.awt.Color(51, 51, 51));
        addbutton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addbutton.setForeground(new java.awt.Color(51, 51, 51));
        addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Request_Money_32px.png"))); // NOI18N
        addbutton.setText("Make Payment");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\vijeyaratnam\\Desktop\\warehouse\\icons8_Megaphone_32px_1.png")); // NOI18N
        jButton4.setText("Send Notification");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_pay_id_1.setEditable(false);
        txt_pay_id_1.setBackground(new java.awt.Color(51, 51, 51));
        txt_pay_id_1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_pay_id_1.setForeground(new java.awt.Color(204, 204, 204));
        txt_pay_id_1.setText("####");
        txt_pay_id_1.setBorder(null);
        txt_pay_id_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pay_id_1ActionPerformed(evt);
            }
        });

        due_date.setDateFormatString("yyyy-M-d");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_Restart_32px_1.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_pay_id_1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colstat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton4)))
                .addGap(54, 54, 54)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coldate, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(due_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(addbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txt_pay_id_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(due_date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coldate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(colstat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29))))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_delidate.setDateFormatString("yyyy-M-d");

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(51, 51, 51));
        txt_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 255, 255));
        txt_total.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_retid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ordid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_retname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_delidate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ordid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_retid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_retname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel25))
                    .addComponent(txt_delidate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N

        p_history.setBackground(new java.awt.Color(51, 51, 51));
        p_history.setForeground(new java.awt.Color(255, 255, 255));
        p_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        p_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_historyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(p_history);

        lbl_total.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Collected");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total To Be Collected");

        txt_ptotal.setBackground(new java.awt.Color(51, 51, 51));
        txt_ptotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_ptotal.setForeground(new java.awt.Color(255, 255, 255));
        txt_ptotal.setText("0.00");

        lbl_percent.setBackground(new java.awt.Color(51, 51, 51));
        lbl_percent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_percent.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Balance (if any)");

        lbl_balance.setBackground(new java.awt.Color(51, 51, 51));
        lbl_balance.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_balance.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons8_High_Priority_32px_1.png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_percent, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ptotal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ptotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_percent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(jLabel2)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        retailer_mail.setEditable(false);
        retailer_mail.setBackground(new java.awt.Color(51, 51, 51));
        retailer_mail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retailer_mail.setForeground(new java.awt.Color(51, 51, 51));
        retailer_mail.setBorder(null);
        retailer_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retailer_mailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(retailer_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(retailer_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void set_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set_tableMouseClicked
       int row = set_table.getSelectedRow();
        String row_id = set_table.getValueAt(row, 0).toString();
        
        try{
            String q = "Select * from set_payment p, retailer r, delivery d where p.ord_id = '"+row_id+"' and p.ret_id=r.ret_id and p.ord_id=d.deliveryID";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            
            if (rs.next())
            {
                String OrderId = rs.getString("ord_id");
                String RetId = rs.getString("ret_id");
               
                String RetName = rs.getString("ret_name");
                String rmail = rs.getString("email");
               // String DeliDate = rs.getString("deliverydate");
                              
                txt_ordid.setText(OrderId);
                txt_retid.setText(RetId);
               
                txt_retname.setText(RetName);
                txt_delidate.setDate(rs.getDate("deliverydate"));
                retailer_mail.setText(rmail);
             }
            
            }
        
        catch( Exception e)
        {
            System.out.println(e);
        }
        
         try{
            String q = "Select pay_id as 'Payment Id', amou as 'Amount', stat as 'Status', set_date as 'Settled Date' from set_payment where ord_id = '"+row_id+"' ";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            p_history.setModel(DbUtils.resultSetToTableModel(rs));
            
            
             }
            
            
        
        catch( Exception e)
        {
            System.out.println(e);
        }
         
         try{
            String sql = "Select SUM(total) from order_1 where ord_id ='"+txt_ordid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            
            while(rs.next()){
                String total_1 = rs.getString("SUM(total)");
                txt_total.setText(total_1);
            }
        }
        catch(Exception e){
            
        }
         
         try{
            String sql = "Select total from order_details where ord_id ='"+txt_ordid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            
            while(rs.next()){
                String total_1 = rs.getString("total");
                lbl_total.setText(total_1);
            }
        }
        catch(Exception e){
            
        }
         
         try{
            String sql = "Select SUM(amou),stat from set_payment where ord_id ='"+txt_ordid.getText()+"' and stat='Collected'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            double zero=0.0;
            while(rs.next()){
                String total_1 = rs.getString("SUM(amou)");
                String sta =rs.getString("stat");
               
                if("Collected".equals(sta))
                
              {
                    txt_ptotal.setText(total_1);}
            
            else{
                    txt_ptotal.setText(Double.toString(zero));
                    
                }
            }
        }
        catch(Exception e){
            
        }
         
         double coltotal = Double.parseDouble(txt_ptotal.getText());
         double totamount = Double.parseDouble(lbl_total.getText());
         double balance = totamount-coltotal;
         double excess = coltotal-totamount;
         
         if(coltotal<totamount)
         {
        double balpercent = ((balance/totamount)*100);
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent1 = Double.parseDouble(df.format(balpercent));
        lbl_balance.setForeground(Color.white);
        lbl_balance.setText(Double.toString(balance));
        lbl_percent.setForeground(Color.red);
          jLabel4.setVisible(false);
        lbl_percent.setText(+trimpercent1+ "% of the total has to be collected");
        
         }
         
         if(coltotal==totamount)
         {
             lbl_balance.setForeground(Color.black);
             lbl_balance.setText("0.00");
             lbl_percent.setForeground(Color.green);
               jLabel4.setVisible(false);
             lbl_percent.setText("Total amount of the order has been collected");
         }
        
         if(coltotal>totamount)
         {
               jLabel4.setVisible(true);
             lbl_percent.setForeground(Color.red);
             lbl_percent.setText("Rupees "+excess+ "has been collected in extra");
         }
         
         
         jTextArea1.append("Order ID: " +txt_ordid.getText()+"\n" );
         jTextArea1.append("Retailer Name: " +txt_retname.getText()+"\n" );
         jTextArea1.append("Total Collected: " +txt_ptotal.getText()+"\n" );
         jTextArea1.append(lbl_percent.getText()+"\n" );
         jTextArea1.setVisible(false);
         
         
        
    }//GEN-LAST:event_set_tableMouseClicked

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed

    private void colstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colstatActionPerformed
        String status = "Collected";
        String colstatus = colstat.getSelectedItem().toString();
        int stat = colstatus.compareTo(status);
        
        if (stat==0)
        {
            coldate.setEnabled(true);
            
        }
        
        else
        {
            coldate.setEnabled(false);
        }
    }//GEN-LAST:event_colstatActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        payment p1 = new payment();
        if (coldate.getDate() == null) 
        {
        JOptionPane.showMessageDialog(this, "Collection Date is required.");
       
        }
        
        else{
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String col_date = date_format.format(coldate.getDate());
        
        SimpleDateFormat date_format1 = new SimpleDateFormat("yyyy-MM-dd");
        String due_date1 = date_format1.format(due_date.getDate());
        
        String pay_id_1 = txt_pay_id_1.getText();
        String amt = txt_amount.getText();
        String stat = colstat.getSelectedItem().toString();
        
        p1.setColDate(col_date);
        p1.setDueDate(due_date1);
        p1.setStat(stat);
        p1.setAmount(amt);
        
        p1.updatecol(pay_id_1);
        
            try{
            String q = "Select pay_id as 'Payment Id', amou as 'Amount', stat as 'Status', set_date as 'Settled Date' from set_payment where ord_id = '"+txt_ordid.getText()+"' ";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            p_history.setModel(DbUtils.resultSetToTableModel(rs));
            
            
             }
            
            
        
        catch( Exception e)
        {
            System.out.println(e);
        }
            
            try{
            String sql = "Select SUM(amou) from set_payment where ord_id ='"+txt_ordid.getText()+"' and stat='collected'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            
            while(rs.next()){
                String total_1 = rs.getString("SUM(amou)");
                txt_ptotal.setText(total_1);
            }
        }
        catch(Exception e){
            
        }
             double coltotal = Double.parseDouble(txt_ptotal.getText());
         double totamount = Double.parseDouble(lbl_total.getText());
         double balance = totamount-coltotal;
         double excess = coltotal-totamount;
         
         if(coltotal<totamount)
         {
        double balpercent = ((balance/totamount)*100);
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent1 = Double.parseDouble(df.format(balpercent));
        lbl_balance.setText(Double.toString(balance));
        lbl_percent.setForeground(Color.red);
        lbl_percent.setText(+trimpercent1+ "% of the total has to be collected");
         }
         
         if(coltotal==totamount)
         {
             lbl_balance.setForeground(Color.black);
             lbl_balance.setText("0.00");
             lbl_percent.setForeground(Color.green);
             lbl_percent.setText("Total amount of the order has been collected");
         }
        
         if(coltotal>totamount)
         {
             jLabel4.setVisible(true);
             lbl_percent.setText("Rupees "+excess+ "has been collected in extra");
         }
            
        } 
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String to = retailer_mail.getText();
        String subject1 = txt_ordid.getText();
        String message = jTextArea1.getText();
        
        String user = "warehouseitp@gmail.com";
        String pass = "warehouse123";
        
        Mail m1 = new Mail();
        m1.send(to,subject1,message,user,pass);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_pay_id_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pay_id_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pay_id_1ActionPerformed

    private void p_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_historyMouseClicked
        int row_1 = p_history.getSelectedRow();
        String row_id_1 = p_history.getValueAt(row_1, 0).toString();
        
        try{
            String q = "Select amou, stat, due_date, pay_id, set_date from set_payment where pay_id = '"+row_id_1+"' ";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            
            while (rs.next())
            {
                
                String payid = rs.getString("pay_id");
                String amount_1 = rs.getString("amou");
                //String due_date_1 = rs.getDate("due_date");
                String stat1 = rs.getString("stat");
                
                if("Not Collected".equals(stat1)){
                
                colstat.setSelectedIndex(0);
              
                }
                else{
                
                colstat.setSelectedIndex(1);
                
                }
                txt_pay_id_1.setText(payid);
                txt_amount.setText(amount_1);
                due_date.setDate(rs.getDate("due_date"));
                coldate.setDate(rs.getDate("set_date"));
                
                
             }
            
            }
        
        catch( Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_p_historyMouseClicked

    private void txt_ordidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ordidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ordidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      payment p1 = new payment();
             
        
        SimpleDateFormat date_format1 = new SimpleDateFormat("yyyy-MM-dd");
        String due_date1 = date_format1.format(due_date.getDate());
        
        String pay_id_1 = txt_pay_id_1.getText();
        String amt = txt_amount.getText();
        String stat = colstat.getSelectedItem().toString();
        
        p1.setDueDate(due_date1);
        p1.setStat(stat);
        p1.setAmount(amt);
        
        p1.updatedue(pay_id_1);
        
            try{
            String q = "Select pay_id as 'Payment Id', amou as 'Amount', stat as 'Status', set_date as 'Settled Date' from set_payment where ord_id = '"+txt_ordid.getText()+"' ";
           PreparedStatement pst = con.prepareStatement(q);
            rs= pst.executeQuery();
            p_history.setModel(DbUtils.resultSetToTableModel(rs));
            
            
             }
            
            
        
        catch( Exception e)
        {
            System.out.println(e);
        }
            
            try{
            String sql = "Select SUM(amou) from set_payment where ord_id ='"+txt_ordid.getText()+"' and stat='collected'";
            PreparedStatement pst = con.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            
            while(rs.next()){
                String total_1 = rs.getString("SUM(amou)");
                txt_ptotal.setText(total_1);
            }
        }
        catch(Exception e){
            
        }
             double coltotal = Double.parseDouble(txt_ptotal.getText());
         double totamount = Double.parseDouble(lbl_total.getText());
         double balance = totamount-coltotal;
         double excess = coltotal-totamount;
         
         if(coltotal<totamount)
         {
        double balpercent = ((balance/totamount)*100);
        DecimalFormat df = new DecimalFormat("#.##");
        double trimpercent1 = Double.parseDouble(df.format(balpercent));
        lbl_balance.setText(Double.toString(balance));
        lbl_percent.setForeground(Color.red);
        lbl_percent.setText(+trimpercent1+ "% of the total has to be collected");
         }
         
         if(coltotal==totamount)
         {
             lbl_balance.setForeground(Color.black);
             lbl_balance.setText("0.00");
             lbl_percent.setForeground(Color.green);
             lbl_percent.setText("Total amount of the order has been collected");
         }
        
         if(coltotal>totamount)
         {
             lbl_percent.setText("Rupees "+excess+ "has been collected in extra");
         }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void retailer_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retailer_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retailer_mailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private com.toedter.calendar.JDateChooser coldate;
    private javax.swing.JComboBox<String> colstat;
    private com.toedter.calendar.JDateChooser due_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_percent;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable p_history;
    private javax.swing.JTextField retailer_mail;
    private javax.swing.JTable set_table;
    private javax.swing.JTextField txt_amount;
    private com.toedter.calendar.JDateChooser txt_delidate;
    private javax.swing.JTextField txt_ordid;
    private javax.swing.JTextField txt_pay_id_1;
    private javax.swing.JLabel txt_ptotal;
    private javax.swing.JTextField txt_retid;
    private javax.swing.JTextField txt_retname;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
